[package]
name = "generate_ballot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
minifb = "0.25.0"
plotly = "0.8.4"
rand = "0.8.5"
